import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";
import Nav from "@/components/nav/nav";
import { MovieClientProvider } from "@/lib/tmdb/MovieClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <div className="min-h-full bg-linear-to-b from-gray-50 to-[#a3a7aa]">
          <div className="w-full flex items-center justify-center p-20">
            <div className="grow max-w-250">
              <Nav />
              <div className="bg-white shadow-md">
                <MovieClientProvider>
                  <ReactQueryProvider>
                    {children}
                  </ReactQueryProvider>
                </MovieClientProvider>
              </div>
            </div>
          </div>
       </div>
      </body>
    </html>
  );
}
